services:
  mariadb:
    image: mariadb:10.11
    container_name: secureasset-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: secureasset
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
